DROP DATABASE IF EXISTS workshop;
CREATE DATABASE workshop;
USE workshop;
CREATE TABLE personas (
    ID INT AUTO_INCREMENT,
    NOMBRE_USUARIO VARCHAR(15),
    PASSWORD VARCHAR(15),
    NOMBRE VARCHAR(30),
    APELLIDO VARCHAR(30),
    DNI INT,
    ISADMIN ENUM("T", "F"),
    PRIMARY KEY(ID, NOMBRE_USUARIO)
);
CREATE TABLE asistencias (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_PERSONA INT,
    ID_EVENTO INT,
    FECHA_HORA DATE
);
CREATE TABLE eventos(
    ID INT AUTO_INCREMENT,
    DESCRIPCION VARCHAR(100),
    LUGAR VARCHAR(50),
    FECHA DATE,
    TIPO_EVENTO INT,
    CAPACIDAD INT,
    ESTADO ENUM("P", "C", "A"),
    PRIMARY KEY(ID)
);
CREATE TABLE tipo_eventos(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(80)
);